name: 'Terraform Plan: Integration Environment'

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'environments/integration/**'
      - '.github/workflows/terraform-apply-integration.yml'


permissions:
  contents: read
  pull-requests: write

jobs:
  terraform_plan_integration:
    name: 'Terraform Plan for Integration'
    runs-on: ubuntu-latest
    environment: integration
    env:
      TF_INTEGRATION_DIR: './environments/integration'
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   # --- TODO: Add AWS OIDC ---
    #   - name: Configure AWS credentials (OIDC)
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/GitHubActionsTerraformRole # ЗАМІНИ НА СВІЙ ARN
    #       aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Integration: route53_cert
      - name: Terraform Init (integration/route53_cert)
        id: init_route53_cert_integration
        run: terraform init -input=false
        working-directory: ${{ env.TF_INTEGRATION_DIR }}/route53_cert
        continue-on-error: true

      - name: Terraform Plan (integration/route53_cert)
        id: plan_route53_cert_integration
        run: |
          terraform plan -input=false -no-color -detailed-exitcode \
            > route53_cert_integration.plan
          echo "tf_actions_plan_exit_code=$?" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_INTEGRATION_DIR }}/route53_cert
        continue-on-error: true

      # Integration: frontend
      - name: Terraform Init (integration/frontend)
        id: init_frontend_integration
        run: terraform init -input=false
        working-directory: ${{ env.TF_INTEGRATION_DIR }}/frontend
        continue-on-error: true

      - name: Terraform Plan (integration/frontend)
        id: plan_frontend_integration
        run: |
          terraform plan -input=false -no-color -detailed-exitcode \
            > frontend_integration.plan
          echo "tf_actions_plan_exit_code=$?" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_INTEGRATION_DIR }}/frontend
        continue-on-error: true

      # Integration: backend
      - name: Terraform Init (integration/backend)
        id: init_backend_integration
        run: terraform init -input=false
        working-directory: ${{ env.TF_INTEGRATION_DIR }}/backend
        continue-on-error: true

      - name: Terraform Plan (integration/backend)
        id: plan_backend_integration
        run: |
          terraform plan -input=false -no-color -detailed-exitcode \
            > backend_integration.plan
          echo "tf_actions_plan_exit_code=$?" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_INTEGRATION_DIR }}/backend
        continue-on-error: true

      - name: Prepare Plan Output for Comment
        id: prepare_comment
        run: |
          comment_body="### Terraform Plan for Integration Environment\n\n" # Один \n тут достатньо

          # Функція для форматування виводу плану
          format_plan_output() {
            local component_name="$1"
            local init_outcome="$2"
            local plan_exit_code="$3"
            local plan_file_path="$4"
            local output=""

            output+="<details><summary>${component_name} Plan (integration)</summary>\n\n" # Один \n
            if [ "${init_outcome}" == "failure" ]; then
              output+="\`\`\`text\nTerraform Init FAILED for ${component_name}\n\`\`\`\n"
            elif [ "${plan_exit_code}" == "1" ]; then
              output+="\`\`\`text\nTerraform Plan FAILED for ${component_name}:\n" # Повідомлення про помилку плану
              output+="$(cat ${plan_file_path} 2>/dev/null || echo 'Error reading plan file or plan file is empty.')\n" # Читаємо вміст файлу
              output+="\`\`\`\n"
            elif [ ! -s "${plan_file_path}" ] && [ "${plan_exit_code}" == "0" ]; then # Якщо файл порожній І exit code 0 (немає змін)
              output+="\`\`\`text\nNo changes. Your infrastructure matches the configuration.\n\`\`\`\n"
            elif [ ! -s "${plan_file_path}" ] && [ "${plan_exit_code}" == "2" ]; then # Якщо файл порожній І exit code 2 (мали бути зміни, але файл порожній - дивно)
              output+="\`\`\`text\nPlan indicates changes, but the plan output file is empty. Please check logs.\n\`\`\`\n"
            else # Якщо є вміст у файлі
              output+="\`\`\`terraform\n"
              output+="$(cat ${plan_file_path} 2>/dev/null || echo 'Error reading plan file.')\n"
              output+="\`\`\`\n"
            fi
            output+="</details>\n\n" # Один \n
            echo -n "$output" # Використовуємо echo -n, щоб уникнути зайвого \n від самого echo
          }

          comment_body+=$(format_plan_output "Route53 & Cert" \
            "${{ steps.init_route53_cert_integration.outcome }}" \
            "${{ steps.plan_route53_cert_integration.outputs.tf_actions_plan_exit_code }}" \
            "${{ env.TF_INTEGRATION_DIR }}/route53_cert/route53_cert_integration.plan")

          comment_body+=$(format_plan_output "Frontend" \
            "${{ steps.init_frontend_integration.outcome }}" \
            "${{ steps.plan_frontend_integration.outputs.tf_actions_plan_exit_code }}" \
            "${{ env.TF_INTEGRATION_DIR }}/frontend/frontend_integration.plan")

          comment_body+=$(format_plan_output "Backend" \
            "${{ steps.init_backend_integration.outcome }}" \
            "${{ steps.plan_backend_integration.outputs.tf_actions_plan_exit_code }}" \
            "${{ env.TF_INTEGRATION_DIR }}/backend/backend_integration.plan")

          MAX_LENGTH=60000
          if [ ${#comment_body} -gt $MAX_LENGTH ]; then
            comment_body="${comment_body:0:$MAX_LENGTH}...\n\n**Note: Plan output was truncated due to GitHub comment length limits.**"
          fi
          # comment_body=$(echo -e "${comment_body}" | sed '/^$/N;/^\n$/D') # Видаляє послідовні порожні рядки

          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo -e "${comment_body}" >> $GITHUB_OUTPUT # Використовуємо echo -e для обробки \n
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Add Plan to PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan-integration
          message: ${{ steps.prepare_comment.outputs.comment }}

      - name: Check for plan errors or changes
        if: steps.plan_route53_cert_integration.outputs.tf_actions_plan_exit_code == '1' || steps.plan_frontend_integration.outputs.tf_actions_plan_exit_code == '1' || steps.plan_backend_integration.outputs.tf_actions_plan_exit_code == '1'
        run: |
          echo "::error::One or more Terraform plan steps failed or had errors."
          exit 1